In [2]:
import pandas as pd
import os
from pathlib import Path
from pathlib import PurePosixPath



BASE_DIR = Path("../").resolve().parent

result_file_path = BASE_DIR / "resources" / "data" / "stack-overflow-survey" / "results.csv"
result_file_schema = BASE_DIR /  "resources" / "data" / "stack-overflow-survey" / "schema.csv"

BASE_DIR,result_file_path,result_file_schema



pd.set_option('display.max_columns',170)
pd.set_option('display.max_rows',170)
pd.set_option('display.max_colwidth',172)
pd.set_option('display.max_seq_items', None)

survey_schema=pd.read_csv(result_file_schema,index_col='qname')
survey_df = pd.read_csv(result_file_path, index_col='ResponseId')

In [88]:
data = {
    "first": ["Ramesh","Rajesh","Mahesh",'Kajoo'],
    "last" : ["Govardhan","singh","pablo",'Singh'],
    "age": [23,34,22,22],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com",'kajoor@mail.com'],
    "language": [['python','scala','golang'],['scala','golang'],['python','scala','golang'],['scala','golang']]

}

df = pd.DataFrame(data)
df

    first       last  age            email                 language
0  Ramesh  Govardhan   23  ramesh@mail.com  [python, scala, golang]
1  Rajesh      singh   34  rajesh@mail.com          [scala, golang]
2  Mahesh      pablo   22  mahesh@mail.com  [python, scala, golang]
3   Kajoo      Singh   22  kajoor@mail.com          [scala, golang]

In [89]:
exploded_df = df.explode('language')
exploded_df

    first       last  age            email language
0  Ramesh  Govardhan   23  ramesh@mail.com   python
0  Ramesh  Govardhan   23  ramesh@mail.com    scala
0  Ramesh  Govardhan   23  ramesh@mail.com   golang
1  Rajesh      singh   34  rajesh@mail.com    scala
1  Rajesh      singh   34  rajesh@mail.com   golang
2  Mahesh      pablo   22  mahesh@mail.com   python
2  Mahesh      pablo   22  mahesh@mail.com    scala
2  Mahesh      pablo   22  mahesh@mail.com   golang
3   Kajoo      Singh   22  kajoor@mail.com    scala
3   Kajoo      Singh   22  kajoor@mail.com   golang

The output 40 means that 40% of all language instances recorded for 22-year-olds are scala (and another 40% are golang).

It is calculating the percentage relative to the total number of skills mentioned, not the total number of unique people!

In [90]:
exploded_df.groupby('age')['language'].value_counts(normalize=True)

age  language
22   scala       0.400000
     golang      0.400000
     python      0.200000
23   python      0.333333
     scala       0.333333
     golang      0.333333
34   scala       0.500000
     golang      0.500000
Name: proportion, dtype: float64

In [94]:
exploded_df.groupby('age')['language'].value_counts()

age  language
22   scala       2
     golang      2
     python      1
23   python      1
     scala       1
     golang      1
34   scala       1
     golang      1
Name: count, dtype: int64

In [95]:
df['age'].value_counts()

age
22    2
23    1
34    1
Name: count, dtype: int64

In [91]:
# 1. Get the total number of unique people for each age from the original dataframe
age_counts = df['age'].value_counts()

# 2. Get the raw counts of languages from the exploded dataframe
lang_counts = exploded_df.groupby('age')['language'].value_counts()

# 3. Divide the language counts by the total number of people in that age bracket
percentage_by_people = (lang_counts / age_counts) * 100
print(percentage_by_people)

age  language
22   scala       100.0
     golang      100.0
     python       50.0
23   python      100.0
     scala       100.0
     golang      100.0
34   scala       100.0
     golang      100.0
Name: count, dtype: float64

In [ ]:
survey_df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='str')

In [ ]:
survey_df[['ConvertedCompYearly',"CompTotal"]]

            ConvertedCompYearly  CompTotal
ResponseId
1                           NaN        NaN
2                           NaN        NaN
3                           NaN        NaN
4                           NaN        NaN
5                           NaN        NaN
...                         ...        ...
65433                       NaN        NaN
65434                       NaN        NaN
65435                       NaN        NaN
65436                       NaN        NaN
65437                       NaN        NaN

[65437 rows x 2 columns]

In [1]:
# survey_df.dtypes

In [ ]:
survey_schema.loc['ICorPM']

qid                                                         QID287
question      Are you an individual contributor or people manager?
force_resp                                                   False
type                                                            MC
selector                                                      SAVR
Name: ICorPM, dtype: object

In [ ]:
survey_df[['ConvertedCompYearly','CompTotal']].median()

ConvertedCompYearly     65000.0
CompTotal              110000.0
dtype: float64

In [ ]:
survey_df[['ConvertedCompYearly','CompTotal']].describe()

       ConvertedCompYearly      CompTotal
count         2.343500e+04   3.374000e+04
mean          8.615529e+04  2.963841e+145
std           1.867570e+05  5.444117e+147
min           1.000000e+00   0.000000e+00
25%           3.271200e+04   6.000000e+04
50%           6.500000e+04   1.100000e+05
75%           1.079715e+05   2.500000e+05
max           1.625660e+07  1.000000e+150

In [ ]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [ ]:
survey_df[['ConvertedCompYearly','CompTotal']].describe()

,ConvertedCompYearly,CompTotal
count,23435.00,33740.00
mean,86155.29,29638411381149976434844996221255135810973346761641119443102059683642337023745002072541016011726778410233362892066394456411829798103125811458473984.00
std,186756.97,5444117135142297852662284923089891085287507383810550263112532649055881882177265287407295512315682219200529825363197301258665890740227694357794258944.00
min,1.00,0.00
25%,32712.00,60000.00
50%,65000.00,110000.00
75%,107971.50,250000.00
max,16256603.00,1000000000000000162545277246339097227904071986031452381501504981983615182576228378136120296965701983510464738707067395631197433897752887331883780669440.00

In [ ]:
survey_df.shape

(65437, 113)

In [ ]:
survey_df['ConvertedCompYearly'].count()

np.int64(23435)

In [ ]:
survey_df['Employment'].value_counts()

In [17]:
survey_df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Haiti                                                       1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [25]:
survey_df['Country'] = survey_df['Country'].map(lambda x: str(x).strip())

In [26]:
country_group = survey_df.groupby('Country')

In [31]:
india_df = country_group.get_group('India')

In [37]:
country_group.count()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
Country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,56,56,56,40,56,40,56,53,34,20,48,35,49,32,33,33,31,31,38,24,47,45,41,37,33,30,28,23,23,34,29,26,18,14,14,20,18,17,34,29,28,39,34,32,41,34,29,21,20,35,30,28,30,25,24,50,46,45,32,43,45,52,37,27,29,29,24,15,10,5,4,9,2,4,34,33,23,28,19,20,15,14,14,12,12,12,12,11,11,16,15,15,20,19,17,16,20,20,19,21,21,21,21,21,21,21,21,21,42,40,12,19
Albania,49,49,49,38,49,38,49,47,29,21,44,37,47,32,32,28,26,31,34,16,43,36,30,37,29,24,33,25,21,32,26,24,13,11,8,30,23,18,35,29,25,37,33,30,42,39,30,21,18,38,31,28,31,26,26,47,45,45,32,45,44,48,41,31,32,31,27,23,20,7,5,16,4,2,41,31,30,32,19,18,16,14,14,14,15,14,13,14,15,15,14,13,15,16,16,16,16,16,16,18,18,18,18,18,18,18,18,18,41,39,11,16
Algeria,77,77,77,49,77,49,77,77,59,47,75,52,73,41,40,41,38,37,41,19,75,72,64,67,63,58,53,50,42,63,59,53,26,21,17,51,47,40,68,62,60,69,66,64,70,65,46,41,39,66,59,57,65,60,59,74,73,73,60,72,73,74,63,53,55,56,52,46,29,18,21,29,11,4,62,53,48,34,21,20,20,18,18,18,18,18,18,18,17,19,19,19,20,20,20,18,19,20,20,21,21,21,21,21,21,21,21,21,69,70,10,20
Andorra,15,15,15,10,15,10,15,14,12,9,14,12,14,9,9,9,9,9,10,6,14,14,12,10,9,7,9,8,5,8,8,7,6,4,3,7,5,4,9,9,9,12,11,11,12,9,8,6,6,12,11,10,10,7,6,13,12,12,8,12,12,14,9,6,6,6,6,4,4,3,2,6,0,0,8,7,8,7,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,11,2,2
Angola,20,20,20,15,20,14,20,18,13,9,18,13,17,11,9,10,9,10,13,6,18,17,12,18,17,14,15,12,9,17,14,9,10,8,6,14,11,9,13,11,9,15,14,11,16,16,11,9,9,14,12,10,13,11,10,19,15,15,9,15,15,20,17,12,11,11,10,7,3,2,1,8,1,1,15,14,13,12,9,7,7,7,6,7,7,6,6,7,6,8,8,8,8,8,8,7,8,8,8,10,10,10,10,10,10,10,10,10,16,15,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Viet Nam,296,296,296,200,296,199,296,296,245,199,293,207,294,179,178,174,176,175,181,92,286,266,230,245,210,183,204,174,151,232,200,185,100,62,55,194,159,139,249,218,206,278,250,243,276,242,222,183,174,257,212,201,247,214,200,287,285,285,219,283,283,290,259,212,214,213,195,172,132,96,67,131,25,11,257,230,221,180,135,135,129,123,126,126,125,125,123,123,121,122,123,115,129,128,124,123,128,130,130,134,134,135,135,135,135,135,135,135,268,271,64,132
Yemen,18,18,18,12,18,12,18,17,14,11,17,12,17,8,9,7,7,8,10,5,14,13,12,13,12,10,11,8,5,13,12,11,8,3,3,12,9,8,13,11,11,14,12,12,14,12,10,8,8,11,9,9,13,11,11,17,16,16,15,15,16,17,16,13,13,14,13,9,6,5,3,7,1,3,16,13,12,5,3,2,2,2,1,1,1,1,1,1,1,0,0,1,3,2,3,2,2,2,3,3,3,3,3,3,3,3,3,3,15,13,5,3
Zambia,15,15,15,12,15,12,15,14,10,7,14,8,15,8,9,9,9,9,9,8,13,13,10,12,11,9,11,8,7,12,12,10,7,6,6,9,8,7,13,11,11,13,11,11,15,14,8,6,6,13,10,10,13,9,9,15,12,12,10,11,12,15,14,11,11,11,11,8,1,4,4,5,1,0,14,13,12,6,6,6,6,5,6,6,6,6,6,6,6,6,6,5,6,6,5,6,6,6,6,6,6,6,6,6,6,6,6,6,14,15,5,6
Zimbabwe,26,26,26,20,26,20,26,26,23,19,25,22,26,18,18,18,18,18,18,15,26,25,20,26,25,21,23,20,19,26,20,20,10,9,9,21,17,15,26,22,21,26,25,24,26,25,19,18,18,24,21,21,23,23,22,26,25,25,23,25,25,26,24,22,22,22,19,17,7,13,5,13,1,1,24,23,22,17,14,14,13,13,13,13,13,13,13,13,13,13,13,13,13,14,14,13,14,14,14,14,14,14,14,14,14,14,14,14,24,25,11,14
nan,6507,6507,6507,5316,6507,4974,1854,1746,1153,744,1283,1216,1116,1045,1005,742,401,144,0,0,2066,1800,1507,1575,1216,1027,1241,969,835,1265,992,857,532,364,339,901,685,609,1054,844,778,1070,890,851,1071,909,742,526,494,786,605,569,617,495,474,1985,1891,1888,1219,1680,1653,2464,2173,1760,1738,1681,1234,1056,789,375,318,622,99,74,1258,938,643,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [41]:
survey_schema.loc['LearnCodeOnline']

qid                                                                              QID281
question      What online resources do you use to learn to code? Select all that apply.
force_resp                                                                        False
type                                                                                 MC
selector                                                                           MAVR
Name: LearnCodeOnline, dtype: object

In [46]:
country_group['OfficeStackSyncAdmired'].value_counts()

Country      OfficeStackSyncAdmired
Afghanistan  Cisco Webex Teams                                 3
             Google Meet                                       2
             Discord                                           2
             Telegram;Whatsapp;Zoom                            1
             IRC                                               1
                                                              ..
nan          Google Meet;Skype;Slack;Telegram;Whatsapp;Zoom    1
             Signal;Skype                                      1
             Mattermost;Microsoft Teams;Zoom                   1
             Rocketchat                                        1
             Discord;Microsoft Teams;Slack;Zoom                1
Name: count, Length: 12072, dtype: int64

In [49]:
country_group['OfficeStackSyncAdmired'].value_counts().loc['China']

OfficeStackSyncAdmired
Discord                                                    26
Discord;Telegram                                           25
Telegram                                                   20
Microsoft Teams                                            12
Zoom                                                        9
Slack;Zoom                                                  5
Discord;Slack                                               5
Slack                                                       4
Microsoft Teams;Zoom                                        4
Discord;Matrix                                              3
Discord;Telegram;Zoom                                       3
Whatsapp                                                    3
Google Meet                                                 3
Discord;IRC;Matrix;Telegram                                 2
Discord;Microsoft Teams                                     2
Google Meet;Zoom                                            2
Microsoft Teams;Slack                                       2
Discord;Google Meet;Telegram;Zoom                           2
Discord;Slack;Zoom                                          2
Discord;Google Meet                                         2
Cisco Webex Teams                                           1
Discord;Mattermost;Telegram                                 1
Discord;Microsoft Teams;Slack;Zoom                          1
Discord;Slack;Telegram;Zoom                                 1
Discord;Google Chat;Telegram                                1
Discord;Whatsapp                                            1
Google Chat;Zoom                                            1
Cisco Webex Teams;Slack;Telegram                            1
Discord;Microsoft Teams;Skype;Slack                         1
Google Meet;Skype;Slack;Telegram;Whatsapp;Zoom              1
IRC                                                         1
Discord;Slack;Telegram                                      1
Discord;Jitsi;Zulip                                         1
Zoom;Zulip                                                  1
Telegram;Zoom                                               1
Discord;IRC;Mattermost;Telegram;Whatsapp                    1
Discord;Google Chat;Google Meet;Slack;Telegram;Whatsapp     1
Discord;IRC;Jitsi;Telegram                                  1
IRC;Matrix;Telegram                                         1
Whatsapp;Zoom                                               1
Cisco Webex Teams;Microsoft Teams;Slack                     1
Discord;Matrix;Telegram                                     1
Discord;Microsoft Teams;Telegram;Zoom                       1
Discord;Google Meet;Skype;Telegram                          1
Matrix                                                      1
Microsoft Teams;Telegram                                    1
Discord;Telegram;Whatsapp                                   1
Discord;IRC;Skype;Slack;Telegram                            1
Telegram;Whatsapp;Zoom                                      1
Google Chat;Google Meet;Signal;Slack;Whatsapp               1
Discord;Zoom                                                1
Ringcentral                                                 1
Slack;Telegram                                              1
Discord;Google Meet;Slack;Zoom                              1
Microsoft Teams;Skype;Slack;Zoom                            1
Name: count, dtype: int64

In [44]:
survey_df.head(10)

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Stack Exchange network,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum, online community)",Technical documentation;Blogs;Books;Written Tutorials;Stack Overflow,API document(s) and/or SDK document(s);User guides or README files found in the source repository;First-party knowledge base;Traditional public search engine,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern Ireland,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Kotlin;Python;TypeScript,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies);Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliable guidance from community-vetted answers;Showcase expertise with code solutions;Engage with community by commenting on que...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other (please specify):,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)",Technical documentation;Blogs;Books;Written Tutorials;Stack Overflow;Coding sessions (live or recorded);Social Media,API document(s) and/or SDK document(s);User guides or README files found in the source repository;Traditional public search engine,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern Ireland,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow Blog or Podcast,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliable guidance from community-vetted answers;Showcase expertise with code solutions;Engage with community by commenting on que...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning a degree,"Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc);Online Courses or Certification",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;Python;SQL;TypeScript,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL;TypeScript,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL;TypeScript,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Improve collaboration;Speed up learning;Improve accuracy in coding,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Writing code;Documenting code;Debugging and getting help;Deployment and monitoring;Search for answers;Generating content or s...,Testing code;Committing and reviewing code;Predictive analytics,NaN,Learning about a codebase;Project planning;Writing code;Documenting code;Debugging and getting help;Deployment and monitoring;Search for answers;Generating content or s...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;Missing or incorrect attribution for sources of data,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)","Other online resources (e.g., videos, blogs, forum, online community)",Technical documentation;Blogs;Written Tutorials;Stack Overflow;Social Media;Video-based Online Courses,API document(s) and/or SDK document(s);User guides or README files found in the source repository;First-party knowledge base;Traditional public search engine,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stack Overflow for Teams,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies);Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with community by commenting on questions and answers or voting on questions and answers;Learning new-to-me technology/techniques;...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online Courses or Certification",NaN,NaN,10,NaN,Student,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);HTML/CSS;Java;JavaScript;Python;Rust;Swift;TypeScript,Bash/Shell (all shells);HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,Bash/Shell (all shells);HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,Cloud Firestore,Cloud Firestore,Cloud Firestore,Cloudflare,Cloudflare,Cloudflare,Node.js,Node.js,Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NaN,NaN,NaN,Docker;Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Homebrew;npm;Pip;pnpm,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,Nano;Vim;Visual Studio Code;Xcode,iOS;MacOS;Ubuntu,NaN,Markdown File,Markdown File,Markdown File,Discord,Discord,Discord,ChatGPT;GitHub Copilot;OpenAI Codex,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliable guidance from community-vetted answers;Showcase expertise with code solutions;Engage with community by commenting on que...,"Yes, definitely",Yes,Favorable,Increase productivity;Greater efficiency;Improve accuracy in coding,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Debugging and getting help,Documenting code;Testing code;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Search for answers;Generating content or synthetic data,Learning about a codebase;Project planning,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,No,Circulating misinformation or disinformation;Missing or incorrect attribution for sources of data;Replacing jobs without options for new employment opportunities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
7,"I am not primarily a developer, but I write code sometimes as part of my work/studies",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, forum, online community)",Technical documentation;Stack Overflow;Written-based Online Courses,NaN,7,7,Academic researcher,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,R,R,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RStudio,RStudio,RStudio,MacOS,MacOS,NaN,NaN,NaN,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,Microsoft Teams;Whatsapp,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Quickly finding code solutions;Finding reliable guidance from community-vetted answers;Engage with community by commenting on questions and answers or voting on questio...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN,NaN
8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking for work",NaN,Apples,NaN,"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)","Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification;Coding Bootcamp",Technical documentation;Video-based Online Courses,First-party knowledge base,1,NaN,Student,NaN,NaN,NaN,NaN,NaN,Uzbekistan,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,Supabase,Supabase,Supabase,Firebase;Netlify;Vercel,Vercel,Vercel,Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Vite;Yarn,npm;Vite,npm;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Jira,NaN,NaN,Google Meet;Telegram;Zoom,Google Meet;Telegram,Google Meet;Telegram,ChatGPT,ChatGPT,ChatGPT,Stack Overflow,Less than once per month or monthly,No,NaN,Quickly finding code solutions;Finding reliable guidance from community-vetted answers,"No, not at all",Yes,Indifferent,Increase productivity;Speed up learning;Improve accuracy in coding,Somewhat distrust,Bad at handling complex tasks,Writing code;Debugging and getting help;Search for answers,Project planning;Testing code,NaN,NaN,NaN,Writing code;Debugging and getting help;Search for answers,NaN,NaN,Yes,Circulating misinformation or disinformation;Missing or incorrect attribution for sources of data;Replacing jobs without options for new employment opportunities,"Don’t trust the output or answers;AI tools lack context of codebase, internal architecture, and/or company knowledge",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN
9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification",Stack Overflow;Written-based Online Courses,NaN,20,NaN,Academic researcher,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern Ireland,NaN,NaN,Lua,Lua,Lua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Visual Studio Code,Visual Studio Code,MacOS,MacOS,NaN,NaN,NaN,Skype,Skype,Skype,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Engage with community by commenting on questions and answers or voting on questions and answers,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-employed",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","On the job training;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)",Technical documentation;Blogs;Written Tutorials;Stack Overflow;How-to videos,Traditional public search engine;AI-powered search/dev tool (free),15,11,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Serbia,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Firebase;Vercel,Amazon Web Services (AWS);Digital Ocean;Firebase;Vercel,Amazon Web Services (AWS);Digital Ocean;Firebase;Vercel,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Windows,Jira,Jira,Jira,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Increase productivity;Speed up learning,Neither trust nor distrust,Bad at handling complex tasks,Search for answers,NaN,NaN,NaN,Search for answers,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN

In [54]:
country_group['ConvertedCompYearly'].median().loc['Germany']

np.float64(73036.0)

In [58]:
country_group['ConvertedCompYearly'].agg(['mean','median']).loc['India']

mean      30513.611379
median    16749.000000
Name: India, dtype: float64

In [ ]:
# find how many people is using python coutry wise

In [69]:
country_group['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan     26
Albania         10
Algeria         37
Andorra          8
Angola           9
              ...
Viet Nam       138
Yemen           10
Zambia           8
Zimbabwe        17
nan            998
Name: LanguageHaveWorkedWith, Length: 186, dtype: int64

In [73]:
country_group['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan     26
Albania         10
Algeria         37
Andorra          8
Angola           9
              ...
Viet Nam       138
Yemen           10
Zambia           8
Zimbabwe        17
nan            998
Name: LanguageHaveWorkedWith, Length: 186, dtype: int64

In [ ]:
# What % of people from each country know Python ?

In [33]:
survey_df['ProgrammingLanguage'] = survey_df['LanguageHaveWorkedWith'].str.split(";")

exploded_survey_df=survey_df.explode('ProgrammingLanguage')

In [35]:
exploded_survey_df['ProgrammingLanguage']

ResponseId
1                            NaN
2        Bash/Shell (all shells)
2                             Go
2                       HTML/CSS
2                           Java
                  ...
65437                       Java
65437                 JavaScript
65437                        PHP
65437                     Python
65437                 TypeScript
Name: ProgrammingLanguage, Length: 327925, dtype: str

In [41]:

df = (exploded_survey_df
.groupby(by=['Country'])['ProgrammingLanguage']
.value_counts(normalize=True)
)

In [85]:
df.loc['India']

ProgrammingLanguage
JavaScript                 0.134390
HTML/CSS                   0.114305
Python                     0.104755
SQL                        0.097765
Java                       0.076253
TypeScript                 0.069164
C++                        0.055479
C                          0.053362
Bash/Shell (all shells)    0.037363
PHP                        0.035542
C#                         0.031752
Go                         0.022054
Dart                       0.020085
Kotlin                     0.018559
PowerShell                 0.017377
Rust                       0.013981
MATLAB                     0.010288
Visual Basic (.Net)        0.008172
R                          0.007236
Assembly                   0.006941
Swift                      0.006941
Lua                        0.006449
Ruby                       0.006104
Objective-C                0.004430
Groovy                     0.004283
Solidity                   0.004234
VBA                        0.004037
Scala                      0.003249
MicroPython                0.002560
Perl                       0.002461
GDScript                   0.002412
Elixir                     0.001723
Ada                        0.001575
Haskell                    0.001526
Clojure                    0.001477
Apex                       0.001329
Julia                      0.001280
Zig                        0.001280
Lisp                       0.001231
Cobol                      0.001181
Fortran                    0.001132
Prolog                     0.000985
OCaml                      0.000689
Erlang                     0.000640
Crystal                    0.000541
Nim                        0.000492
F#                         0.000345
Delphi                     0.000295
Zephyr                     0.000295
Name: proportion, dtype: float64

In [45]:
# Corry solution

In [48]:
country_count = survey_df['Country'].value_counts()
country_count

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Haiti                                                       1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [51]:
type(survey_df.groupby('Country')['LanguageHaveWorkedWith'])

pandas.api.typing.SeriesGroupBy

In [79]:
country_using_python = survey_df.groupby('Country')['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

country_using_python

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [80]:
new_df = pd.concat([country_count,country_using_python], axis='columns', sort=False)
new_df

,count,LanguageHaveWorkedWith
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
Haiti,1,0
Nauru,1,0
Chad,1,1
Djibouti,1,0
Solomon Islands,1,0

In [81]:
new_df['knowPython'] = (new_df['LanguageHaveWorkedWith']/new_df['count'])*100

In [78]:
new_df

,count,LanguageHaveWorkedWith,knowPython
Country,,,
United States of America,11095,6251,56.340694
Germany,4947,2647,53.507176
India,4231,2128,50.295438
United Kingdom of Great Britain and Northern Ireland,3224,1638,50.806452
Ukraine,2672,963,36.040419
...,...,...,...
Haiti,1,0,0.000000
Nauru,1,0,0.000000
Chad,1,1,100.000000
Djibouti,1,0,0.000000
Solomon Islands,1,0,0.000000