In [1]:
import pandas as pd
import os
from pathlib import Path
from pathlib import PurePosixPath



BASE_DIR = Path("../").resolve().parent

result_file_path = BASE_DIR / "resources" / "data" / "stack-overflow-survey" / "results.csv"
result_file_schema = BASE_DIR /  "resources" / "data" / "stack-overflow-survey" / "schema.csv"

BASE_DIR,result_file_path,result_file_schema

(PosixPath('/home/suanki/Desktop/overflowwithpyspark'),
 PosixPath('/home/suanki/Desktop/overflowwithpyspark/resources/data/stack-overflow-survey/results.csv'),
 PosixPath('/home/suanki/Desktop/overflowwithpyspark/resources/data/stack-overflow-survey/schema.csv'))

In [ ]:
pd.set_option('display.max_columns',170)
pd.set_option('display.max_rows',170)
pd.set_option('display.max_colwidth',172)

df_schema=pd.read_csv(result_file_schema,index_col='qname')
df = pd.read_csv(result_file_path, index_col='ResponseId')

In [74]:
df_schema=pd.read_csv(result_file_schema,index_col='qname')
df_schema.head()

,qid,question,force_resp,type,selector
qname,,,,,
MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
Age,QID127,What is your age?*,True,MC,SAVR
Employment,QID296,Which of the following best describes your cur...,True,MC,MAVR
RemoteWork,QID308,Which best describes your current work situation?,False,MC,SAVR
Check,QID341,Just checking to make sure you are paying atte...,True,MC,SAVR

In [75]:
df=pd.read_csv(result_file_path)
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='str')

In [76]:

df = pd.read_csv(result_file_path, index_col='ResponseId')

In [77]:
df_schema.index

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'Language', 'Database', 'Platform',
       'Webframe', 'Embedded', 'MiscTech', 'ToolsTech', 'NEWCollabTools',
       'OpSys', 'OfficeStackAsync', 'OfficeStackSync', 'AISearchDev',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOHow',
       'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc', 'AIComplex', 'AITool',
       'AINext', 'AIThreat', 'AIEthics', 'AIChallenges', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge', 'Frequency', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSat', 'JobSatPoints',
       'SOTeamsUsage', 'SurveyLength', 'SurveyEase', 'Knowledge_1',
       'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5',
       'Knowledge_6', 'Knowledge_7', 'Knowledge_8', 'Knowledge_9',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'JobSatPoints_1',
       'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7',
       'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11'],
      dtype='str', name='qname')

In [78]:
df.index

RangeIndex(start=1, stop=65438, step=1, name='ResponseId')

In [79]:
list(df.columns)

['MainBranch',
 'Age',
 'Employment',
 'RemoteWork',
 'Check',
 'CodingActivities',
 'EdLevel',
 'LearnCode',
 'LearnCodeOnline',
 'TechDoc',
 'YearsCode',
 'YearsCodePro',
 'DevType',
 'OrgSize',
 'PurchaseInfluence',
 'BuyNewTool',
 'BuildvsBuy',
 'TechEndorse',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'EmbeddedHaveWorkedWith',
 'EmbeddedWantToWorkWith',
 'EmbeddedAdmired',
 'MiscTechHaveWorkedWith',
 'MiscTechWantToWorkWith',
 'MiscTechAdmired',
 'ToolsTechHaveWorkedWith',
 'ToolsTechWantToWorkWith',
 'ToolsTechAdmired',
 'NEWCollabToolsHaveWorkedWith',
 'NEWCollabToolsWantToWorkWith',
 'NEWCollabToolsAdmired',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackSyncHaveWorkedWith',
 'OfficeStackSyncWantToWorkWith',
 'OfficeStackSyncAdmired',
 'AISearchDevHaveWorkedWith',
 'AISearchDevWantToWorkWith',
 'AISearchDevAdmired',
 'NEWSOSites',
 'SOVisitFreq',
 'SOAccount',
 'SOPartFreq',
 'SOHow',
 'SOComm',
 'AISelect',
 'AISent',
 'AIBen',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently Using',
 'AIToolInterested in Using',
 'AIToolNot interested in Using',
 'AINextMuch more integrated',
 'AINextNo change',
 'AINextMore integrated',
 'AINextLess integrated',
 'AINextMuch less integrated',
 'AIThreat',
 'AIEthics',
 'AIChallenges',
 'TBranch',
 'ICorPM',
 'WorkExp',
 'Knowledge_1',
 'Knowledge_2',
 'Knowledge_3',
 'Knowledge_4',
 'Knowledge_5',
 'Knowledge_6',
 'Knowledge_7',
 'Knowledge_8',
 'Knowledge_9',
 'Frequency_1',
 'Frequency_2',
 'Frequency_3',
 'TimeSearching',
 'TimeAnswering',
 'Frustration',
 'ProfessionalTech',
 'ProfessionalCloud',
 'ProfessionalQuestion',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'SurveyLength',
 'SurveyEase',
 'ConvertedCompYearly',
 'JobSat']

In [11]:
# Tell pandas to display everything in a sequence/index
pd.set_option('display.max_seq_items', None)

In [80]:
df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='str')

In [81]:
df_schema.loc['AIThreat','question']

'Do you believe AI is a threat to your current job?'

In [82]:
df['AIThreat'].value_counts()

AIThreat
No              30423
I'm not sure     8878
Yes              5388
Name: count, dtype: int64

In [83]:
df_schema.sort_index(inplace=True)

In [84]:
df_schema.index

Index(['AIAcc', 'AIBen', 'AIChallenges', 'AIComplex', 'AIEthics', 'AINext',
       'AISearchDev', 'AISelect', 'AISent', 'AIThreat', 'AITool', 'Age',
       'BuildvsBuy', 'BuyNewTool', 'Check', 'CodingActivities', 'CompTotal',
       'Country', 'Currency', 'Database', 'DevType', 'EdLevel', 'Embedded',
       'Employment', 'Frequency', 'Frequency_1', 'Frequency_2', 'Frequency_3',
       'Frustration', 'ICorPM', 'Industry', 'JobSat', 'JobSatPoints',
       'JobSatPoints_1', 'JobSatPoints_10', 'JobSatPoints_11',
       'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7',
       'JobSatPoints_8', 'JobSatPoints_9', 'Knowledge', 'Knowledge_1',
       'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5',
       'Knowledge_6', 'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Language',
       'LearnCode', 'LearnCodeOnline', 'MainBranch', 'MiscTech',
       'NEWCollabTools', 'NEWSOSites', 'OfficeStackAsync', 'OfficeStackSync',
       'OpSys', 'OrgSize', 'Platform', 'ProfessionalCloud',
       'ProfessionalQuestion', 'ProfessionalTech', 'PurchaseInfluence',
       'RemoteWork', 'SOAccount', 'SOComm', 'SOHow', 'SOPartFreq',
       'SOTeamsUsage', 'SOVisitFreq', 'SurveyEase', 'SurveyLength', 'TBranch',
       'TechDoc', 'TechEndorse', 'TimeAnswering', 'TimeSearching', 'ToolsTech',
       'Webframe', 'WorkExp', 'YearsCode', 'YearsCodePro'],
      dtype='str', name='qname')

In [97]:
df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly', 'JobSat'],
      dtype='str')

In [87]:
df_schema.loc['Language','question']

'Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)'

In [93]:
df['LanguageHaveWorkedWith']

ResponseId
1                                                      NaN
2        Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
3                                                       C#
4        C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...
5                  C++;HTML/CSS;JavaScript;Lua;Python;Rust
                               ...
65433                                                  NaN
65434                                                  NaN
65435                                                  NaN
65436             C;C++;Go;Lua;Objective-C;Python;Rust;SQL
65437     C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript
Name: LanguageHaveWorkedWith, Length: 65437, dtype: str

## Filtering

In [94]:
df_schema.loc['CompTotal','question']

'What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions)? Please enter a whole number in the box below, without any punctuation.  If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty. '

In [108]:
filter_by_high_salary = (df['ConvertedCompYearly'] > 70000)

countries_list = ['United States','India', 'United Kingdom', 'Germany']

filter_by_country = df['Country'].isin(countries_list)

filter_by_language = df['LanguageHaveWorkedWith'].str.contains('Scala', na=False)

filter_by_high_salary_and_countries = filter_by_high_salary & filter_by_country & filter_by_language

In [112]:
filter_by_high_salary_and_countries

ResponseId
1        False
2        False
3        False
4        False
5        False
         ...
65433    False
65434    False
65435    False
65436    False
65437    False
Length: 65437, dtype: bool

In [111]:
df.loc[filter_by_high_salary_and_countries, ['Country','Currency','LanguageHaveWorkedWith', 'CompTotal', 'ConvertedCompYearly']]

,Country,Currency,LanguageHaveWorkedWith,CompTotal,ConvertedCompYearly
ResponseId,,,,,
4037,Germany,EUR European Euro,Python;Rust;Scala,120000.0,128887.0
7061,Germany,EUR European Euro,HTML/CSS;Java;JavaScript;Scala;TypeScript,102000.0,109554.0
8006,Germany,EUR European Euro,PowerShell;Python;Scala;SQL;Swift,84000.0,90221.0
8519,India,INR\tIndian rupee,Java;Scala;SQL,9500000.0,113653.0
11983,Germany,EUR European Euro,HTML/CSS;Java;JavaScript;Kotlin;Python;Scala;S...,70000.0,75184.0
12636,Germany,EUR European Euro,Bash/Shell (all shells);Java;JavaScript;Kotlin...,75000.0,80555.0
15398,Germany,EUR European Euro,Bash/Shell (all shells);Java;JavaScript;Kotlin...,80000.0,85925.0
15713,Germany,EUR European Euro,Bash/Shell (all shells);C#;HTML/CSS;Java;JavaS...,66000.0,70888.0
16042,Germany,EUR European Euro,Bash/Shell (all shells);Java;JavaScript;Kotlin...,70000.0,75184.0
17192,Germany,EUR European Euro,Bash/Shell (all shells);HTML/CSS;Java;Kotlin;R...,83000.0,89147.0
17395,Germany,EUR European Euro,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,95000.0,102036.0
20276,Germany,EUR European Euro,Bash/Shell (all shells);Python;Ruby;Rust;Scala,91000.0,97740.0
20901,Germany,EUR European Euro,Bash/Shell (all shells);Java;Rust;Scala;SQL;Ty...,100000.0,107406.0
21671,Germany,EUR European Euro,Java;Python;Rust;Scala,75000.0,80555.0
21880,Germany,EUR European Euro,Bash/Shell (all shells);Go;Scala;SQL,69000.0,74110.0
22089,Germany,EUR European Euro,Haskell;HTML/CSS;Java;Kotlin;Scala;TypeScript,80000.0,85925.0
22402,Germany,EUR European Euro,Bash/Shell (all shells);Kotlin;Scala,90000.0,96666.0
22405,Germany,EUR European Euro,Scala,70000.0,75184.0
22991,Germany,EUR European Euro,Go;HTML/CSS;Python;Rust;Scala;SQL;TypeScript,85000.0,91295.0
22998,Germany,EUR European Euro,Bash/Shell (all shells);Clojure;Go;Python;Scal...,200000.0,214812.0
23340,Germany,EUR European Euro,Bash/Shell (all shells);C;C++;GDScript;Java;Ja...,105000.0,112777.0
23651,Germany,EUR European Euro,Bash/Shell (all shells);C++;HTML/CSS;JavaScrip...,70000.0,75184.0
23841,Germany,EUR European Euro,Bash/Shell (all shells);Groovy;Java;Python;Scala,110000.0,118147.0
24347,Germany,EUR European Euro,Clojure;Groovy;HTML/CSS;Java;JavaScript;MATLAB...,140000.0,150369.0
25739,Germany,EUR European Euro,Scala,80000.0,85925.0
27072,Germany,EUR European Euro,HTML/CSS;JavaScript;Scala;TypeScript,73000.0,78407.0
27584,Germany,EUR European Euro,Scala,120000.0,128887.0
29212,Germany,EUR European Euro,Go;Java;Python;Scala;Visual Basic (.Net),150000.0,161109.0
29365,Germany,EUR European Euro,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,70200.0,75399.0
30565,Germany,EUR European Euro,Bash/Shell (all shells);Groovy;Java;Python;Sca...,120000.0,128887.0
31761,Germany,EUR European Euro,Python;Scala,81000.0,86999.0
32540,Germany,EUR European Euro,Scala;SQL,102400.0,109984.0
32576,Germany,EUR European Euro,Bash/Shell (all shells);GDScript;HTML/CSS;Java...,85000.0,91295.0
32581,Germany,EUR European Euro,Dart;Python;Scala;SQL,89000.0,95592.0
34626,Germany,EUR European Euro,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,105000.0,112777.0
37897,Germany,EUR European Euro,Bash/Shell (all shells);C;Elixir;Go;Groovy;HTM...,82508.0,88619.0
40596,Germany,EUR European Euro,Bash/Shell (all shells);C;Haskell;Java;Python;...,100000.0,107406.0
41026,Germany,EUR European Euro,Go;Kotlin;Python;Rust;Scala;TypeScript,96000.0,103110.0