In [30]:
import pandas as pd
import os
from pathlib import Path
from pathlib import PurePosixPath



BASE_DIR = Path("../").resolve().parent

result_file_path = BASE_DIR / "resources" / "data" / "stack-overflow-survey" / "results.csv"
result_file_schema = BASE_DIR /  "resources" / "data" / "stack-overflow-survey" / "schema.csv"

BASE_DIR,result_file_path,result_file_schema



pd.set_option('display.max_columns',170)
pd.set_option('display.max_rows',170)
pd.set_option('display.max_colwidth',172)
pd.set_option('display.max_seq_items', None)

survey_schema=pd.read_csv(result_file_schema,index_col='qname')
survey_df = pd.read_csv(result_file_path, index_col='ResponseId')

In [2]:
data = {
    "first": ["Ramesh","Rajesh","Mahesh"],
    "last" : ["Govardhan","singh","pablo"],
    "age": [23,34,25],
    "email": ["ramesh@mail.com","rajesh@mail.com","mahesh@mail.com"]

}

df = pd.DataFrame(data)
df

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com

In [6]:
df.sort_values(by='age',ascending=True)

    first       last  age            email
0  Ramesh  Govardhan   23  ramesh@mail.com
2  Mahesh      pablo   25  mahesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com

In [7]:
df.sort_values(by=['first','last'],ascending=True)

    first       last  age            email
2  Mahesh      pablo   25  mahesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
0  Ramesh  Govardhan   23  ramesh@mail.com

In [13]:
df.sort_values(by=['first','last'],ascending=[True,False], inplace=True) # first is asc and last is desc sorting

In [15]:
df

    first       last  age            email
2  Mahesh      pablo   25  mahesh@mail.com
1  Rajesh      singh   34  rajesh@mail.com
0  Ramesh  Govardhan   23  ramesh@mail.com

In [11]:
#reverse sor_value using sort_index

In [17]:
df.sort_index(inplace=True)

## lets look at the survey data

In [19]:
survey_df.head(2)

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Stack Exchange network,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum, online community)",Technical documentation;Blogs;Books;Written Tutorials;Stack Overflow,API document(s) and/or SDK document(s);User guides or README files found in the source repository;First-party knowledge base;Traditional public search engine,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern Ireland,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Kotlin;Python;TypeScript,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sharing & collaboration platform for companies);Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliable guidance from community-vetted answers;Showcase expertise with code solutions;Engage with community by commenting on que...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [26]:
survey_df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith',
       'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'ToolsTechAdmired',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith',
       'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired',
       'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith',
       'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc',
       'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using',
       'AIToolNot interested in Using', 'AINextMuch more integrated',
       'AINextNo change', 'AINextMore integrated', 'AINextLess integrated',
       'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges',
       'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Frustration', 'ProfessionalTech', 'ProfessionalCloud',
       'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
       'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength',
       'SurveyEase', 'SalaryUSD', 'JobSat'],
      dtype='str')

In [31]:
survey_df.rename(columns={"ConvertedCompYearly":"SalaryUSD"}, inplace=True)

In [33]:
# sort the survey result by salary
df = survey_df[['SalaryUSD','Country','RemoteWork','Employment','LanguageHaveWorkedWith']]

In [43]:
df.sort_values(by=['Country','SalaryUSD'],ascending=[True,False], inplace=True)

In [45]:
df[['Country','SalaryUSD']]

                Country  SalaryUSD
ResponseId
39346       Afghanistan    20000.0
37549       Afghanistan    11512.0
14673       Afghanistan     8634.0
6942        Afghanistan     6907.0
1566        Afghanistan     5940.0
...                 ...        ...
65431               NaN        NaN
65433               NaN        NaN
65434               NaN        NaN
65435               NaN        NaN
65437               NaN        NaN

[65437 rows x 2 columns]

In [46]:
# 10 highest salary

In [47]:
df['SalaryUSD'].nlargest(10)

ResponseId
15838    16256603.0
12724    13818022.0
28380     9000000.0
17594     6340564.0
17673     4936778.0
19268     3367716.0
23695     2584118.0
33721     2237846.0
34524     2153432.0
13764     2048046.0
Name: SalaryUSD, dtype: float64